config/routes.rb
Rails.application.routes.draw do

  get 'daily_sheet/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :payment_details
  resources :payments
  get 'welcome/index'
  resources :footwears
  resources :sale_details
  resources :sales
  resources :way_pays
  resources :trademarks
  resources :clients
  resources :categories
  resources :release_countries
  resources :sizes
  resources :seasons
  resources :colors
  resources :providers

  get 'welcome/index/:day/:month/:year' => 'welcome#index'
  get 'welcome/index'

  get 'payments/new/:id' => 'payments#new'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'get_retail_price/:id' => 'footwears#get_retail_price'

  post 'get_fees/:total' => 'way_pays#get_fees'

  post 'get_client_debt/:id' => 'clients#get_client_debt'

  post 'get_way_pay_interest/:id/:fee' => 'way_pays#get_way_pay_interest'

  post 'get_footwear_id/:sku' => 'footwears#get_footwear_id'



end

app/models/season.rb
class Season < ApplicationRecord
	def to_s
		name
	end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:name, :note)
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_with(model: season, local: true) do |form| %>
  <% if season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="actions">
    <%= link_to 'Volver', :back, class: "btn btn-primary" %>
    <%= form.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=seasons_path%>">Temporadas</a>
  </li>
  <li class="breadcrumb-item active">Editar Temporada</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Editar Temporada</div>
    <div class="card-body">
      <%= render 'form', season: @season %>
    </div>
  </div>
</div>

app/views/seasons/index.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item active">Temporadas</li>

</ol>

<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-table"></i>
    Temporadas</div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="datatable">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Notas</th>
            <th>Opciones</th>
          </tr>
        </thead>

        <tbody>
          <% @seasons.each do |season| %>
            <tr>
              <td><%= season.name %></td>
              <td><%= season.note %></td>
              <td>
                <%= link_to((fa_icon "eye"), season) %>
                <%= link_to((fa_icon "pencil"), edit_season_path(season)) %>
                <%= link_to((fa_icon "trash-o"), season, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
<%= link_to 'Volver', :back, class: "btn btn-primary" %>
<%= link_to 'Cargar Temporada', new_season_path, class: 'btn btn-primary' %>

app/views/seasons/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=providers_path%>">Tempradas</a>
  </li>
  <li class="breadcrumb-item active">Crear Temporada</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Crear Temporada</div>
    <div class="card-body">
      <%= render 'form', season: @season %>
    </div>
  </div>
</div>

app/views/seasons/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=seasons_path%>">Temporadas</a>
  </li>
  <li class="breadcrumb-item active"><%= @season.name %></li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header"><%= @season.name %></div>
    <div class="card-body">
    	<p>
		  <strong>Name:</strong>
		  <%= @season.name %>
		</p>

		<p>
		  <strong>Note:</strong>
		  <%= @season.note %>
		</p>
      <div class="text-center">
        <%= link_to 'Volver', :back, class: "btn btn-primary" %>
      	<%= link_to 'Editar', edit_season_path(@season), class: "btn btn-primary" %>      	
      </div>
    </div>
  </div>
</div>