config/routes.rb
Rails.application.routes.draw do

  get 'daily_sheet/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :payment_details
  resources :payments
  get 'welcome/index'
  resources :footwears
  resources :sale_details
  resources :sales
  resources :way_pays
  resources :trademarks
  resources :clients
  resources :categories
  resources :release_countries
  resources :sizes
  resources :seasons
  resources :colors
  resources :providers

  get 'welcome/index/:day/:month/:year' => 'welcome#index'
  get 'welcome/index'

  get 'payments/new/:id' => 'payments#new'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'get_retail_price/:id' => 'footwears#get_retail_price'

  post 'get_fees/:total' => 'way_pays#get_fees'

  post 'get_client_debt/:id' => 'clients#get_client_debt'

  post 'get_way_pay_interest/:id/:fee' => 'way_pays#get_way_pay_interest'

  post 'get_footwear_id/:sku' => 'footwears#get_footwear_id'



end

app/models/footwear.rb
class Footwear < ApplicationRecord
  belongs_to :trademark
  belongs_to :category
  belongs_to :color
  belongs_to :release_country, optional:true
  belongs_to :size
  belongs_to :season, optional:true

  validates_presence_of :stock
  validates_presence_of :stock_warning
  validates_presence_of :wholesale_price
  validates_presence_of :color_id
  validates_presence_of :size_id
  validates_presence_of :trademark
  validates_presence_of :category


  has_one_attached :avatar
  
  def get_select_description
    if article.nil? or article.blank? 
      "(" + self.sku + ") " + self.category.to_s + " " + self.trademark.to_s
    else
      "(" + self.sku + ") " + self.category.to_s + " " + self.article
    end
  end

  def create_sku
    sku = self.sku
    calc = (((sku [1].to_i + sku[3].to_i + sku[5].to_i + sku[7].to_i + sku[9].to_i + sku[11].to_i) * 3) + (sku[0].to_i + sku[2].to_i + sku[4].to_i + sku[6].to_i + sku[8].to_i + sku[10].to_i)).digits.first
    if calc > 0
      verification_value = 10 - calc
    else
      verification_value = 0
    end

  	self.sku = '779999' + (sprintf '%06d', id) + verification_value.to_s
  end

  
  def get_barcode
    if self.sku[0] == 7
      bar_code = Barby::PngOutputter.new(Barby::EAN13.new(self.sku[0..11]))
    else
      bar_code = Barby::PngOutputter.new(Barby::Code39.new(self.sku[0..14],true))
    end
    bar_code.margin = 1 
    bar_code.height = 60
    bar_code.xdim = 1
    
    File.open('app/assets/images/barcode.png', 'wb'){|f| f.write bar_code.to_png }
    
  end


  def get_retail_price
    if !retail_price.nil? and retail_price.to_i != 0
      retail_price
    else
      wholesale_price * 2.2
    end
  end

  def calculate_way_pay(way_pay_name, monthly)
    if WayPay.where(name: way_pay_name).first.get_index(monthly).nil?
      return nil
    else
      if self.retail_price.nil?
        self.retail_price = self.wholesale_price * 2.2
      end
      return self.retail_price * WayPay.where(name: way_pay_name).first.get_index(monthly)
    end
  end

  def dec_stock(count)
    self.stock = self.stock - count
  end

  def inc_stock(count)
    self.stock = self.stock + count
  end

  def to_s
    sku
  end

end

app/controllers/footwears_controller.rb
class FootwearsController < ApplicationController
  before_action :set_footwear, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token



  # GET /footwears
  # GET /footwears.json
  def index
    @footwears = Footwear.all
  end

  # GET /footwears/1
  # GET /footwears/1.json
  def show
    @footwear.get_barcode
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template:'footwears/template', pdf:'Nombre', page_size: nil, page_width:'1.8in', page_height:'1.2in', margin:{top:'0.1in', bottom:'0.01in',left:'0.0in',right:'0.0in'}}
    end
  end

  # GET /footwears/new
  def new
    @footwear = Footwear.new
  end

  # GET /footwears/1/edit
  def edit
  end

  # POST /footwears
  # POST /footwears.json
  def create
    @footwear = Footwear.new(footwear_params)
    
      
    respond_to do |format|
      if @footwear.save
        if @footwear.sku.blank?
          @footwear.create_sku()
        end

        if @footwear.short_description.blank?
          @footwear.short_description = @footwear.category.to_s + " " + @footwear.trademark.to_s + " " + @footwear.size.to_s + " " + @footwear.color.to_s
        end

        if @footwear.retail_price.nil?
          @footwear.retail_price = @footwear.wholesale_price * 2.2
        end

        @footwear.save
        format.html { redirect_to @footwear, notice: 'Footwear was successfully created.' }
        format.json { render :show, status: :created, location: @footwear }
      else
        format.html { render :new }
        format.json { render json: @footwear.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /get_footwear_value/1
  def get_retail_price
    id = params[:id]
    retail_price = Footwear.where(id:id).first.get_retail_price
    respond_to do |format|
      format.json  { render :json => {:function => "get_retail_price", :retail_price => retail_price}}
    end

  end


  def get_footwear_id
    sku = params[:sku]
    id = Footwear.where(sku:sku).first.id
    respond_to do |format|
      format.json  { render :json => {:function => "get_footwear_id", :id => id}}
    end
    
  end


  # PATCH/PUT /footwears/1
  # PATCH/PUT /footwears/1.json
  def update
    respond_to do |format|
      if @footwear.update(footwear_params)
        if @footwear.sku.blank?
          @footwear.create_sku()
        end
        if @footwear.short_description.blank?
          @footwear.short_description = @footwear.category.to_s + " " + @footwear.trademark.to_s + " " + @footwear.size.to_s + " " + @footwear.color.to_s
        end
        @footwear.save
        format.html { redirect_to @footwear, notice: 'Footwear was successfully updated.' }
        format.json { render :show, status: :ok, location: @footwear }
      else
        format.html { render :edit }
        format.json { render json: @footwear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /footwears/1
  # DELETE /footwears/1.json
  def destroy
    @footwear.destroy
    respond_to do |format|
      format.html { redirect_to footwears_url, notice: 'Footwear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_footwear
      @footwear = Footwear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def footwear_params
      params.require(:footwear).permit(:sku, :article, :trademark_id, :category_id, :color_id, :stock, :stock_warning, :wholesale_price, :wholesale_price, :retail_price, :retail_price, :gender, :active, :short_description, :long_description, :release_date, :release_country_id, :size_id, :weight, :season_id, :avatar, :sex, :ean13_code)
    end
end

app/helpers/footwears_helper.rb
module FootwearsHelper
end

app/views/footwears/_form.html.erb
<%= form_with(model: footwear, local: true, html: { class: "form-horizontal" }) do |form| %>
  <% if footwear.errors.any? %>
    <script type="text/javascript">
      <% footwear.errors.full_messages.each do |message| %>
        toastr['error']('<%= message %>');
      <% end %>
    </script>
  <% end %>

  <div class="field row">
    <%= form.label :sku, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.text_field :sku %>
    </div>
    <%= form.label :article, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.text_field :article %>
    </div>
  </div>

  <div class="field row">
    <%= form.label :trademark_id, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.collection_select :trademark_id, Trademark.all, :id, :to_s, {prompt: "Seleccionar"}, {class: "select2 select-field"} %>
    </div>
    <%= form.label :category_id, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.collection_select :category_id, Category.all, :id, :to_s, {prompt: "Seleccionar"}, {class: "select2 select-field"} %>
    </div>
  </div>

  <div class="field row">
    <%= form.label :sex, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.select :sex, ["Masculino", "Femenino"], {prompt: "Seleccionar"}, {class: "select2"} %>
    </div>
    <%= form.label :color_id, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.collection_select :color_id, Color.all, :id, :to_s, {prompt: "Seleccionar"}, {class: "select2 select-field"} %>
    </div>
  </div>

  <div class="field row">
    <%= form.label :size_id, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.collection_select :size_id, Size.all, :id, :to_s, {prompt: "Seleccionar"}, {class: "select2 select-field"} %>
    </div>
    <%= form.label :season_id, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.collection_select :season_id, Season.all, :id, :to_s, {prompt: "Seleccionar"}, {class: "select2 select-field"} %>
    </div>
  </div>


  <div class="field row">
    <%= form.label :release_date, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <% if form.object.release_date.nil?%>
        <%= form.text_field :release_date, :class => "datepicker", :value=>""%>
      <% else %>
        <%= form.text_field :release_date, :class => "datepicker", :value=>"#{form.object.release_date.strftime("%d/%m/%Y") unless form.object.new_record?}"%>
      <% end %>


    </div>
    <%= form.label :release_country_id, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.collection_select :release_country_id, ReleaseCountry.all, :id, :to_s, {}, {:class => "select2 select-field"} %>
    </div>
  </div>

  <hr>
  <div class="field row">
    <%= form.label :stock, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.number_field :stock, :placeholder => "0" %>
    </div>
    <%= form.label :stock_warning, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.number_field :stock_warning, :placeholder => "0" %>
    </div>
  </div>
  <div class="field row">
    <%= form.label :wholesale_price, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4 input-icon">
      <%= form.number_field :wholesale_price, :placeholder => "0.00" %>
      <i>$</i>
    </div>
    <%= form.label :retail_price, :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-4 input-icon">
      <%= form.number_field :retail_price, :placeholder => "0.00" %>
      <i>$</i>
    </div>
  </div>

  <hr>

  <div class="field">
    <%= form.label :long_description %>
    <%= form.text_area :long_description %>
  </div>


  <div class="field">
    <%= form.check_box :active, :checked=> "checked" %>
    <span style="font-style: italic;font-size: 0.8rem;"> Si el producto no se encuentra disponible para la venta, quite el tílde de esta casilla</span>
  </div>

  <div class="field">
    <%= form.label "Imagen" %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= link_to 'Volver', :back, class: "btn btn-primary" %>
    <%= form.submit %>
  </div>
<% end %>

app/views/footwears/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=footwears_path%>">Calzados</a>
  </li>
  <li class="breadcrumb-item active">Editar Calzado</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5" style="max-width: 53rem;">
    <div class="card-header">Editar Calzado</div>
    <div class="card-body">
      <%= render 'form', footwear: @footwear %>
    </div>
  </div>
</div>

app/views/footwears/index.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item active">Calzados</li>

</ol>

<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-table"></i>
    Calzados</div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="datatable">
        <thead>
          <tr>
            <th>Sku</th>
            <th>Artículo</th>
            <th>Marca</th>
            <th>Categoría</th>
            <th>Inventario</th>
            <th>Talle</th>
            <th>Opciones</th>
          </tr>
        </thead>

        <tbody>
          <% @footwears.each do |footwear| %>
            <tr>
              <td><%= footwear.sku %></td>
              <td><%= footwear.article %></td>
              <td><span class="dot" style="background-color:<%= footwear.color.hex_code %>;width:15px;height: 15px;"></span> <%= footwear.trademark %></td>
              <td><%= footwear.category %></td>
              <td><%= footwear.stock %></td>
              <td><%= footwear.size %></td>
              <td>
                <%= link_to((fa_icon "eye"), footwear) %>
                <%= link_to((fa_icon "pencil"), edit_footwear_path(footwear)) %>
                <%= link_to((fa_icon "trash-o"), footwear, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
<%= link_to 'Volver', colors_path, class: "btn btn-primary" %>
<%= link_to 'Crear Calzado', new_footwear_path, class: 'btn btn-primary' %>

app/views/footwears/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=footwears_path%>">Calzados</a>
  </li>
  <li class="breadcrumb-item active">Crear Calzado</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5"  style="max-width: 53rem;">
    <div class="card-header">Crear Calzado</div>
    <div class="card-body">
      <%= render 'form', footwear: @footwear %>
    </div>
  </div>
</div>

app/views/footwears/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=footwears_path%>">Calzados</a>
  </li>
  <li class="breadcrumb-item active"><%= @footwear.sku %></li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5" style="max-width: 53rem;">
    <div class="card-header active-<%=@footwear.active%>"><%= @footwear.short_description %></div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-12">
          <% if  @footwear.stock > @footwear.stock_warning %>
            <div class="alert alert-success" role="alert">
             Quedan <strong><%=@footwear.stock%></strong> ejemplares en el inventario.
            </div>
          <% else %>            
            <div class="alert alert-danger" role="alert">
              Quedan <strong><%=@footwear.stock%></strong> ejemplar<% if  @footwear.stock > 2 %>es<% end %> en el inventario, debería solictar más.
            </div>
          <% end %>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <% if @footwear.avatar.attached? %>
              <img src="<%=url_for(@footwear.avatar)%>" class="" alt="San Fran" style="width:204px;height:auto;"> 
            <% else %>
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT47Iy_5Ta74Q-2vZ4YhSNbSUYDAFtCsP6ABoHkZBaU3kG9RBOA" class="img-fluid img-thumbnail" alt="San Fran" style="width:204px;height:auto;">
            <% end %>
          
          </div>
          <div style="width: 100%;text-align:center;">
            <%= image_tag "barcode.png", class: "center-block" %>
          </div>
     
          
          <div style="max-width: 100%;text-align: center;">
            <%= @footwear.sku %>
          </div>

          <%= link_to image_tag("print_button.png", class: :float_button, alt: "Imprimir"), footwears_path+"/"+@footwear.id.to_s+".pdf", target: :_blank %>

        </div>
        <div class="col-md-8">
          <% if !@footwear.article.nil? and  !@footwear.article.blank?%>
            <p>
              <strong>Artículo:</strong>
              <%= @footwear.article%>
            </p>
          <% end %>
          <p>
            <strong>Marca (proveedor):</strong>
            <%= @footwear.trademark%>
          </p>
          <p>
            <strong>Categoría:</strong>
            <%= @footwear.category %>
          </p>
          <p>
            <strong>Sexo:</strong>
            <%= @footwear.sex %>
          </p>
          <p>
            <strong>Color:</strong>
            <%= @footwear.color %>
          </p>
          <p>
            <strong>Talle:</strong>
            <%= @footwear.size %>
          </p>
          <% if !@footwear.release_date.nil?%>
           <p>
            <strong>Fecha de creación:</strong>
            <%= @footwear.release_date.strftime("%d/%m/%Y") %>
          </p>
          <% end %>
          <p>
            <strong>País de origen:</strong>
            <%= @footwear.release_country %>
          </p>
          
          
        </div>


        <div class="col-md-12">
          <br>
          <ul class="list-group">
            <li class="list-group-item">
              Precio de Lista
              <span style="float:right;"><%= number_to_currency(@footwear.wholesale_price) %></span>
            </li>
            <li class="list-group-item">
              Precio Contado/Debito
              <span style="float:right;">
                <% if  @footwear.retail_price.nil? %>
                  <%= number_to_currency(@footwear.wholesale_price * WayPay.first.c1) %>
                <% else %>
                  <%= number_to_currency(@footwear.retail_price) %>
                <% end %>
              </span>
            </li>

            <li class="list-group-item">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Tajerta</th>
                    <th scope="col">3 cuotas</th>
                    <th scope="col">6 cuotas</th>
                    <th scope="col">9 cuotas</th>
                    <th scope="col">12 coutas</th>
                  </tr>
                </thead>
                <tbody>
                  <% WayPay.all.each do |wp| %>
                    <% if wp.name.upcase != "DEBITO" and wp.name.upcase != "EFECTIVO" %>
                      <tr>
                        <td><%=wp.name%></td>
                        <td>
                          <% if !@footwear.calculate_way_pay(wp.name, 3).nil?%>
                            <%= number_to_currency(@footwear.calculate_way_pay(wp.name, 3) / 3)%>  (<%= number_to_currency(@footwear.calculate_way_pay(wp.name, 3),) %>)
                          <% else %>  
                            -
                          <% end %>  
                        </td>
                        <td>
                          <% if !@footwear.calculate_way_pay(wp.name, 6).nil?%>
                            <%= number_to_currency(@footwear.calculate_way_pay(wp.name, 6) / 6)%>  (<%= number_to_currency(@footwear.calculate_way_pay(wp.name, 6)) %>)
                          <% else %>  
                            -
                          <% end %>  
                        </td>
                        <td>
                          <% if !@footwear.calculate_way_pay(wp.name, 9).nil?%>
                            <%= number_to_currency(@footwear.calculate_way_pay(wp.name, 9) / 9)%>  (<%= number_to_currency(@footwear.calculate_way_pay(wp.name, 9)) %>)
                          <% else %>  
                            -
                          <% end %>  
                        </td>
                        <td>
                          <% if !@footwear.calculate_way_pay(wp.name, 12).nil?%>
                            <%= number_to_currency(@footwear.calculate_way_pay(wp.name, 12) / 12 )%>  (<%= number_to_currency(@footwear.calculate_way_pay(wp.name, 12)) %>)
                          <% else %>  
                            -
                          <% end %>  
                        </td>
                      </tr>
                    <%end%>
                  <%end%>
                </tbody>
              </table>
            </li>
          </ul>
        </div>
      </div>

      <% if !@footwear.long_description.nil? %>
        <br>
        <p style="font-style: italic"><%=@footwear.long_description%></p>
        <hr>
      <%end%>



      <div class="text-center">
        <%= link_to 'Volver', :back, class: "btn btn-primary" %>
        <%= link_to 'Editar', edit_footwear_path(@footwear), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  
  $('#footwear_release_country_id').val(11).trigger('change');
</script>

app/views/footwears/template.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
  </head>
  <body onload='number_pages'>
		<div id="content">
			<center><%= @footwear.article %> - <%= @footwear.size %></center>
		  <center><%= image_tag wicked_pdf_asset_base64('barcode.png') %></center>
    	<center><%= @footwear.sku %></center>
    </div>
  </body>
</html>