config/routes.rb
Rails.application.routes.draw do

  get 'daily_sheet/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :payment_details
  resources :payments
  get 'welcome/index'
  resources :footwears
  resources :sale_details
  resources :sales
  resources :way_pays
  resources :trademarks
  resources :clients
  resources :categories
  resources :release_countries
  resources :sizes
  resources :seasons
  resources :colors
  resources :providers

  get 'welcome/index/:day/:month/:year' => 'welcome#index'
  get 'welcome/index'

  get 'payments/new/:id' => 'payments#new'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'get_retail_price/:id' => 'footwears#get_retail_price'

  post 'get_fees/:total' => 'way_pays#get_fees'

  post 'get_client_debt/:id' => 'clients#get_client_debt'

  post 'get_way_pay_interest/:id/:fee' => 'way_pays#get_way_pay_interest'

  post 'get_footwear_id/:sku' => 'footwears#get_footwear_id'



end

app/models/color.rb
class Color < ApplicationRecord
	def to_s
		name
	end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: [:show, :edit, :update, :destroy]

  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1
  # PATCH/PUT /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color.destroy
    respond_to do |format|
      format.html { redirect_to colors_url, notice: 'Color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_params
      params.require(:color).permit(:name, :hex_code)
    end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_form.html.erb
<%= form_with(model: color, local: true) do |form| %>
  <% if color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hex_code %>
    <%= form.text_field :hex_code %>
  </div>

  <div class="actions">
    <%= link_to 'Volver', :back, class: "btn btn-primary" %>
    <%= form.submit %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=colors_path%>">Colores</a>
  </li>
  <li class="breadcrumb-item active">Editar Color</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Editar Proveedor</div>
    <div class="card-body">
      <%= render 'form', color: @color %>
    </div>
  </div>
</div>

app/views/colors/index.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item active">Colores</li>

</ol>

<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-table"></i>
    Colores</div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="datatable">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Muestra</th>
            <th>Código Hex</th>
            <th>Opciones</th>
          </tr>
        </thead>

        <tbody>
          <% @colors.each do |color| %>
            <tr>
              <td><%= color.name %></td>
              <td><span class="dot" style="background-color:<%= color.hex_code %>;"></span></td>
              <td><%= color.hex_code %></td>
              <td>
                <%= link_to((fa_icon "eye"), color) %>
                <%= link_to((fa_icon "pencil"), edit_color_path(color)) %>
                <%= link_to((fa_icon "trash-o"), color, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
<%= link_to 'Volver', :back, class: "btn btn-primary" %>
<%= link_to 'Crear Color', new_color_path, class: 'btn btn-primary' %>

app/views/colors/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=providers_path%>">Colores</a>
  </li>
  <li class="breadcrumb-item active">Crear Color</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Crear Proveedor</div>
    <div class="card-body">
      <%= render 'form', color: @color %>
    </div>
  </div>
</div>

app/views/colors/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=colors_path%>">Colores</a>
  </li>
  <li class="breadcrumb-item active"><%= @color.name %></li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header"><%= @color.name %></div>
    <div class="card-body">
    	<p>
		  <strong>Nombre:</strong>
		  <%= @color.name %>
		</p>

		<p>
		  <strong>Muestra:</strong>
		  <span class="dot" style="background-color:<%= @color.hex_code %>;">
		</p>

		<p>
		  <strong>Código Hexadecimal:</strong>
		  <%= @color.hex_code %>
		</p>
		<div class="text-center">
			<%= link_to 'Volver', :back, class: "btn btn-primary" %>
			<%= link_to 'Editar', edit_color_path(@color), class: "btn btn-primary" %>
		</div>
    </div>
  </div>
</div>