config/routes.rb
Rails.application.routes.draw do

  get 'daily_sheet/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :payment_details
  resources :payments
  get 'welcome/index'
  resources :footwears
  resources :sale_details
  resources :sales
  resources :way_pays
  resources :trademarks
  resources :clients
  resources :categories
  resources :release_countries
  resources :sizes
  resources :seasons
  resources :colors
  resources :providers

  get 'welcome/index/:day/:month/:year' => 'welcome#index'
  get 'welcome/index'

  get 'payments/new/:id' => 'payments#new'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'get_retail_price/:id' => 'footwears#get_retail_price'

  post 'get_fees/:total' => 'way_pays#get_fees'

  post 'get_client_debt/:id' => 'clients#get_client_debt'

  post 'get_way_pay_interest/:id/:fee' => 'way_pays#get_way_pay_interest'

  post 'get_footwear_id/:sku' => 'footwears#get_footwear_id'



end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  has_many :sale_details, inverse_of: :sale, dependent: :destroy
  accepts_nested_attributes_for :sale_details, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :client
  validates_presence_of :date_sale

  def get_amount
  	self.sale_details.sum(:real_price).to_f
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale_details = SaleDetail.where(sale: @sale)

  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end


  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    @sale.state = "Iniciada"
    respond_to do |format|
      if @sale.save

        #incrementar stock
        @sale.sale_details.each do |sd|
          if !sd.footwear_id.nil?
            fw = Footwear.where(id:sd.footwear_id).first
            fw.dec_stock(sd.count)
            fw.save
          end
        end



        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      @sale.sale_details.each do |sd|
        if !sd.footwear_id.nil?
          fw = Footwear.where(id:sd.footwear_id).first
          fw.inc_stock(sd.count)
          fw.save
        end
      end


      if @sale.update(sale_params)
        @sale.sale_details.each do |sd|
          if !sd.footwear_id.nil?
            fw = Footwear.where(id:sd.footwear_id).first
            fw.dec_stock(sd.count)
            fw.save
          end
        end
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.sale_details.each do |sd|
      if !sd.footwear_id.nil?
        fw = Footwear.where(id:sd.footwear_id).first
        fw.inc_stock(sd.count)
        fw.save
      end
    end
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:date_sale, :client_id, :state, sale_details_attributes: [:id, :footwear_id, :count, :real_price, :_destroy])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |f| %>
  <% if sale.errors.any? %>
    <script type="text/javascript">
      <% sale.errors.full_messages.each do |message| %>
        toastr['error']('<%= message %>');
      <% end %>
    </script>
  <% end %>
  <div class="field row">
    <div class="col-sm-4">
      <%= f.label :date_sale%>
      <%= f.text_field :date_sale, :class => "datepicker", :value=>"#{f.object.date_sale.strftime("%d/%m/%Y") unless f.object.new_record?}"%>
    </div>
    <div class="col-sm-6">
      <%= f.label :client_id%>
      <%= f.collection_select :client_id, Client.all, :id, :to_s, {prompt: "Seleccionar"}, {class: "select2 select-field", id: "client_select"} %>
    </div>
    <div class="col-sm-2">
      <%= f.label "n", :style=>"color:white;"%>
      <%= link_to_add_association (fa_icon "plus"), f, :sale_details, data: { association_insertion_node: '.sale_details', association_insertion_method: :append }, class: "btn btn-primary btn-block" %>
    </div>
    <hr>

  </div>
  <br>
  <div class="sale_details">
    <%= f.fields_for :sale_details do |sale_details| %>
        <%= render 'sale_detail_fields', :f => sale_details %>
    <% end %>
  </div>

  <hr>
  <div class="col-sm-12" style="text-align: right; font-weight: 600;">
    <p>Total = $ <span id="total">0,00</span></p>
    
  </div>
  <div class="text-center col-md-12">
    <%= link_to 'Volver', :back, class: "btn btn-primary" %>
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/_sale_detail_fields.html.erb
<div class="field nested-fields row">
		<div class="col-sm-2">
			<%= f.label :count%>
			<%= f.number_field :count, {class: "footwear_cant", min:0} %>
			
		</div>
		<div class="col-sm-6">
			<%= f.label :footwear_id %>
			<%= f.collection_select :footwear_id, Footwear.all, :id, :get_select_description, {prompt: "Seleccionar"}, {class: "select2 select-field footwear_select"} %>
		</div>
		<div class="col-sm-3">
			<%= f.label :real_price%>
			<div class="input-icon">
		      <%= f.text_field :real_price, :placeholder => "0.00", :class=>"footwear_value" %>
		      <i>$</i>
		    </div>
		</div>
		<div class="col-sm-1">
			<%= f.label "n", :style=>"color:white;"%>
			<%= link_to_remove_association (fa_icon "times"), f, class: "btn-block", style: "color: red;padding: 3px 0px;font-size: 1.3rem;" %>
		</div>
</div>

app/views/sales/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=sales_path%>">Ventas</a>
  </li>
  <li class="breadcrumb-item active">Editar Venta</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Editar Venta</div>
    <div class="card-body">
      <%= render 'form', sale: @sale %>
    </div>
  </div>
</div>

app/views/sales/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item active">Ventas</li>

</ol>

<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-table"></i>
    Ventas</div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="datatable">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Cliente</th>
            <th>Monto</th>
            <th>Opciones</th>
          </tr>
        </thead>

        <tbody>
          <% @sales.each do |sale| %>
            <tr>
              <td><%= sale.date_sale %></td>
              <td><%= sale.client %></td>
              <td><%= number_to_currency(sale.get_amount) %></td>
              <td>
                <%= link_to((fa_icon "eye"), sale) %>
                <%= link_to((fa_icon "pencil"), edit_sale_path(sale)) %>
                <%= link_to((fa_icon "money"), new_payment_path+"/"+sale.client.id.to_s, {:style=>'color:green;'})  %>
                <%= link_to((fa_icon "trash-o"), sale, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
<%= link_to 'Volver', :back, class: "btn btn-primary" %>
<%= link_to 'Cargar nueva Venta', new_sale_path, class: 'btn btn-primary' %>

app/views/sales/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=sales_path%>">Ventas</a>
  </li>
  <li class="breadcrumb-item active">Crear Venta</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Crear Venta</div>
    <div class="card-body">
      <%= render 'form', sale: @sale %>
      <hr>
      <table id="table-fees"class="table">
        <thead>
          <tr>
            <th scope="col">Tajerta</th>
            <th scope="col">3 cuotas</th>
            <th scope="col">6 cuotas</th>
            <th scope="col">9 cuotas</th>
            <th scope="col">12 coutas</th>
          </tr>
        </thead>
        <tbody>
          
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/sales/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=sales_path%>">Ventas</a>
  </li>
  <li class="breadcrumb-item active"><%= @sale.id %></li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">
    	<div class="row">
    		<div class="col-md-6">Venta Nº: <%= @sale.id %></div>
    		<div clas="col-md-6" style="text-align: right;width: 50%; padding-right:15px">Estado: <%= @sale.state%></div>
    	</div>
	 	</div>
    <div class="card-body row">
    	<div class="col-md-6"> <strong> Fecha: </strong> <%= @sale.date_sale %></div>
		 	<div class="col-md-6" style="text-align: right;"><strong>Cliente: </strong><a href="/clients/<%= @sale.client.id%>"><%= @sale.client %></a></div>
		 	<div class="col-md-12" style="margin-top: 25px;"></div>
		 	<div class="col-md-12">

		 		<table class="table">
		 			<thead>
	          <tr>
	            <th>Cantidad</th>
	            <th>Artículo</th>
	            <th>Detalle</th>
	            <th>Precio</th>
	          </tr>
	        </thead>
		      </tbody>
			    <% @sale.sale_details.each do |sale_details| %>
            <tr>
              <td><%= sale_details.count%></td>
            <% if sale_details.footwear.nil? %>
			        <td></td>
              <td></td>
            <% else %>
              <td><%= sale_details.footwear.article%></td>
              <td><%= sale_details.footwear.short_description%></td>
            <% end %>
              <td><%= number_to_currency(sale_details.real_price)%></td>
			      </tr>
					<% end %>
					</tbody>
				</table>

  		</div>

			<div class="col-sm-12" style="text-align: right; font-weight: 600;">
		    <p>Total = <span><%=number_to_currency(@sale_details.sum(:real_price))%></span></p>
  		</div>
  		<div class="text-center col-md-12">
  			<%= link_to 'Volver', :back, class: "btn btn-primary" %>
		  	<%= link_to 'Editar', edit_sale_path(@sale), class: "btn btn-primary" %>
		  	<%= link_to 'Pagar', new_payment_path+"/"+@sale.client.id.to_s, class: "btn btn-success" %>
		  </div>
  	</div>
	</div>
</div>